version: 2.1

jobs:
  build_and_test:
    macos:
      xcode: "27.0"
    steps:
      - checkout
      - run:
          name: Checkout submodules
          command: git submodule update --init --recursive --depth 1
      - run:
          name: Install xcbeautify
          command: brew list xcbeautify >/dev/null 2>&1 || brew install xcbeautify
      - run:
          name: Build Loop
          command: |
            mkdir -p logs
            set -o pipefail && time xcodebuild -workspace LoopWorkspace.xcworkspace -scheme 'LoopWorkspace' -destination 'platform=iOS Simulator,name=iPhone 17' build 2>&1 | tee logs/build.log | xcbeautify
      - run:
          name: Run Tests
          command: set -o pipefail && time xcodebuild -workspace LoopWorkspace.xcworkspace -scheme 'LoopWorkspace' -destination 'platform=iOS Simulator,name=iPhone 17' -collect-test-diagnostics never test 2>&1 | tee logs/test.log | xcbeautify --report junit --report-path test-results/results.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: logs
      - store_artifacts:
          path: /Users/distiller/Library/Logs/DiagnosticReports
          destination: crashes

workflows:
  build_and_test:
    jobs:
      - build_and_test
